// Conexão ME RH ↔ NR-1: adiciona o hub de prevenção à navegação principal.
(function(){
  const addNR1Link=()=>{
    const nav=document.querySelector('.nav nav');
    if(nav && !nav.querySelector('[href="nr1.html"]')){
      const a=document.createElement('a'); a.href='nr1.html'; a.textContent='NR-1'; a.title='NR-1 · Riscos Psicossociais'; nav.appendChild(a);
    }
  };
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',addNR1Link); else addNR1Link();
})();

const profileData={crescimento:['Seu perfil: Crescimento','Você tende a permanecer onde existe futuro visível. A ME RH responde com trilhas de carreira, PDI, mentoria e oportunidades internas.'],seguranca:['Seu perfil: Segurança','Você valoriza previsibilidade e confiança. A ME RH combina clareza, benefícios, processos e uma relação transparente com a empresa.'],reconhecimento:['Seu perfil: Reconhecimento','Você precisa perceber que seu esforço importa. A ME RH trabalha com feedback, reconhecimento e visibilidade das entregas.'],qualidade:['Seu perfil: Qualidade de vida','Você busca equilíbrio. A ME RH entende que produtividade sustentável nasce de respeito, flexibilidade, saúde e uma vida que continua fora do trabalho.']};
document.querySelectorAll('.choice').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const [title,text]=profileData[btn.dataset.profile];const r=document.getElementById('profile-result');r.innerHTML=`<strong>${title}</strong><p>${text}</p>`;r.classList.remove('hidden');r.scrollIntoView({behavior:'smooth',block:'center'})}));
const salary=document.getElementById('salary'),benefits=document.getElementById('benefits'),salaryLabel=document.getElementById('salaryLabel'),benefitLabel=document.getElementById('benefitLabel'),total=document.getElementById('total'),barSalary=document.getElementById('barSalary'),barBenefits=document.getElementById('barBenefits'),barExperience=document.getElementById('barExperience');
function money(v){return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})}function calc(){const s=+salary.value,b=+benefits.value,e=Math.round(s*.12),t=s+b+e;salaryLabel.textContent=money(s);benefitLabel.textContent=money(b);total.textContent=money(t);barSalary.style.width=`${s/t*100}%`;barBenefits.style.width=`${b/t*100}%`;barExperience.style.width=`${e/t*100}%`}salary.addEventListener('input',calc);benefits.addEventListener('input',calc);document.getElementById('calculate').addEventListener('click',calc);calc();
const periodData={6:[84,91,'8,4%',87],12:[81,88,'10,2%',83],24:[76,82,'13,7%',78]};document.querySelectorAll('.period').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.period').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const d=periodData[btn.dataset.period];document.getElementById('kpiRetention').textContent=d[0]+'%';document.getElementById('kpiClimate').textContent=d[1]+'%';document.getElementById('kpiTurnover').textContent=d[2];document.getElementById('kpiEngagement').textContent=d[3]+'%';}));
const careerData=[['Entrada','Você começa sabendo onde está, o que se espera de você e quais são os primeiros passos para crescer.',['Onboarding humano','Metas claras','Mentoria inicial']],['Desenvolvimento','Aqui o crescimento deixa de ser promessa e vira plano.',['PDI individual','Trilhas de aprendizagem','Feedback contínuo']],['Especialista','Você ganha autonomia, domínio técnico e espaço para gerar impacto.',['Projetos estratégicos','Certificações','Reconhecimento técnico']],['Liderança','Liderar passa a significar desenvolver pessoas e resultados.',['Formação de líderes','1:1 estruturado','Indicadores de pessoas']],['Gestão','A carreira chega à estratégia: decisões que conectam negócio e pessoas.',['Visão sistêmica','People Analytics','Planejamento estratégico']]];
document.querySelectorAll('.career-step').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.career-step').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const d=careerData[+btn.dataset.step];document.getElementById('career-content').innerHTML=`<h3>${d[0]}</h3><p>${d[1]}</p><ul>${d[2].map(x=>`<li>${x}</li>`).join('')}</ul>`}));

// Carrega a camada visual premium sem alterar a estrutura funcional existente.
if(!document.querySelector('link[href="premium.css"]')){const premium=document.createElement('link');premium.rel='stylesheet';premium.href='premium.css';document.head.appendChild(premium);}
