// ME RH — interações, jornada e experiência premium
(function(){
  const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn();
  const addNR1Link=()=>{const nav=document.querySelector('.nav nav');if(nav&&!nav.querySelector('[href="nr1.html"]')){const a=document.createElement('a');a.href='nr1.html';a.textContent='NR-1';a.title='NR-1 · Riscos Psicossociais';nav.appendChild(a)}};
  const addJourney=()=>{
    const career=document.getElementById('carreira'); if(!career||document.getElementById('minha-jornada')) return;
    const section=document.createElement('section'); section.id='minha-jornada'; section.className='section journey-section reveal';
    section.innerHTML=`<div class="container"><div class="section-head"><span class="kicker">06 · MINHA JORNADA ME RH</span><h2>Seu próximo passo não precisa ser <span>uma dúvida.</span></h2><p>Escolha onde você está hoje e descubra o que pode acontecer depois.</p></div><div class="journey-grid"><button class="journey-card active" data-journey="entrada"><span>01</span><strong>Estou chegando</strong><small>Quero ser acolhido e entender a cultura.</small></button><button class="journey-card" data-journey="crescer"><span>02</span><strong>Quero crescer</strong><small>Quero aprender, evoluir e construir carreira.</small></button><button class="journey-card" data-journey="liderar"><span>03</span><strong>Quero liderar</strong><small>Quero desenvolver pessoas e resultados.</small></button><button class="journey-card" data-journey="impactar"><span>04</span><strong>Quero deixar minha marca</strong><small>Quero gerar impacto e participar das decisões.</small></button></div><div class="journey-result" id="journeyResult"><div><span class="journey-icon">→</span><div><strong>Seu começo importa.</strong><p>Você terá clareza sobre sua função, acompanhamento inicial e espaço para fazer perguntas desde o primeiro dia.</p></div></div><div class="journey-points"><span>Onboarding humano</span><span>Integração</span><span>Primeiros 90 dias</span></div></div></div>`;
    career.insertAdjacentElement('afterend',section);
  };
  const addTestimonials=()=>{
    const jobs=document.getElementById('vagas'); if(!jobs||document.getElementById('historias')) return;
    const section=document.createElement('section'); section.id='historias'; section.className='section dark stories-section reveal';
    section.innerHTML=`<div class="container"><div class="section-head"><span class="kicker">07 · HISTÓRIAS QUE INSPIRAM</span><h2>Uma empresa boa para trabalhar é percebida <span>por quem vive.</span></h2><p>Espaço para histórias reais de pessoas, evolução e pertencimento.</p></div><div class="stories-grid"><article class="story"><span class="quote-mark">“</span><p>Entrei buscando uma oportunidade. Encontrei espaço para aprender, ser ouvido e assumir novos desafios.</p><div><strong>Colaborador(a)</strong><small>História de crescimento</small></div></article><article class="story"><span class="quote-mark">“</span><p>Quando tive uma dificuldade, não precisei escolher entre esconder e sair. Pude conversar e construir uma solução.</p><div><strong>Colaborador(a)</strong><small>História de acolhimento</small></div></article><article class="story"><span class="quote-mark">“</span><p>Hoje consigo enxergar meu próximo passo. Isso muda a forma como eu vejo meu trabalho e meu futuro.</p><div><strong>Colaborador(a)</strong><small>História de carreira</small></div></article></div><div class="trust-strip"><span>✓ Escuta ativa</span><span>✓ Carreira visível</span><span>✓ Liderança próxima</span><span>✓ Desenvolvimento contínuo</span></div></div>`;
    jobs.insertAdjacentElement('afterend',section);
  };
  const addMobileMenu=()=>{
    const navWrap=document.querySelector('.nav'); const nav=document.querySelector('.nav nav'); if(!navWrap||!nav||nav.querySelector('.mobile-toggle')) return;
    const toggle=document.createElement('button'); toggle.className='mobile-toggle'; toggle.type='button'; toggle.setAttribute('aria-label','Abrir menu'); toggle.setAttribute('aria-expanded','false'); toggle.innerHTML='<span></span><span></span><span></span>'; navWrap.appendChild(toggle);
    toggle.addEventListener('click',()=>{const open=nav.classList.toggle('mobile-open');toggle.classList.toggle('open',open);toggle.setAttribute('aria-expanded',open?'true':'false')});
    nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('mobile-open');toggle.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
  };
  ready(()=>{
    addNR1Link(); addJourney(); addTestimonials(); addMobileMenu();
    const top=document.querySelector('.topbar'); const scrollState=()=>top&&top.classList.toggle('scrolled',window.scrollY>12); scrollState(); window.addEventListener('scroll',scrollState,{passive:true});
    document.querySelectorAll('.section,.retention-section').forEach(el=>el.classList.add('reveal'));
    const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08}); document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
    const profileData={crescimento:['Seu perfil: Crescimento','Você tende a permanecer onde existe futuro visível. A ME RH responde com trilhas de carreira, PDI, mentoria e oportunidades internas.'],seguranca:['Seu perfil: Segurança','Você valoriza previsibilidade e confiança. A ME RH combina clareza, benefícios, processos e uma relação transparente com a empresa.'],reconhecimento:['Seu perfil: Reconhecimento','Você precisa perceber que seu esforço importa. A ME RH trabalha com feedback, reconhecimento e visibilidade das entregas.'],qualidade:['Seu perfil: Qualidade de vida','Você busca equilíbrio. A ME RH entende que produtividade sustentável nasce de respeito, flexibilidade, saúde e uma vida que continua fora do trabalho.']};
    document.querySelectorAll('.profile-option,.choice').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.profile-option,.choice').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const d=profileData[btn.dataset.profile];const r=document.getElementById('profileResult')||document.getElementById('profile-result');if(d&&r){r.innerHTML=`<strong>${d[0]}</strong><p>${d[1]}</p>`;r.classList.remove('hidden')}}));
    const salary=document.getElementById('salary'),checks=[...document.querySelectorAll('.benefitCheck')],out=document.getElementById('salaryOut'),total=document.getElementById('totalValue'),bar=document.getElementById('valueBar'); const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}); function calc(){if(!salary)return;const s=+salary.value,b=checks.reduce((a,c)=>a+(c.checked?+c.value:0),0),t=s+b;if(out)out.textContent=money(s);if(total)total.textContent=money(t);if(bar)bar.style.width=Math.min(100,t/15000*100)+'%'} if(salary){salary.addEventListener('input',calc);checks.forEach(c=>c.addEventListener('change',calc));calc()}
    const careerData=[['Entrada','Você começa sabendo onde está, o que se espera de você e quais são os primeiros passos para crescer.',['Onboarding humano','Metas claras','Mentoria inicial']],['Desenvolvimento','Aqui o crescimento deixa de ser promessa e vira plano.',['PDI individual','Trilhas de aprendizagem','Feedback contínuo']],['Especialista','Você ganha autonomia, domínio técnico e espaço para gerar impacto.',['Projetos estratégicos','Certificações','Reconhecimento técnico']],['Liderança','Liderar passa a significar desenvolver pessoas e resultados.',['Formação de líderes','1:1 estruturado','Indicadores de pessoas']],['Gestão','A carreira chega à estratégia: decisões que conectam negócio e pessoas.',['Visão sistêmica','People Analytics','Planejamento estratégico']]];
    document.querySelectorAll('.career-step').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.career-step').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const d=careerData[+btn.dataset.step];const r=document.getElementById('careerDetail')||document.getElementById('career-content');if(d&&r)r.innerHTML=`<h3>${d[0]}</h3><p>${d[1]}</p><div class="tags">${d[2].map(x=>`<span class="tag">${x}</span>`).join('')}</div>`}));
    const journeyData={entrada:['Seu começo importa.','Você terá clareza sobre sua função, acompanhamento inicial e espaço para fazer perguntas desde o primeiro dia.',['Onboarding humano','Integração','Primeiros 90 dias']],crescer:['Seu crescimento precisa ser visível.','Transforme vontade em plano: competências, PDI, feedback e oportunidades internas.',['PDI','Trilhas de aprendizagem','Oportunidades internas']],liderar:['Liderança é uma nova responsabilidade.','Antes de liderar resultados, você aprende a liderar relações, conversas e desenvolvimento.',['Formação de líderes','1:1','Gestão de conflitos']],impactar:['Sua marca aparece no impacto.','Projetos, indicadores e decisões passam a conectar sua contribuição ao futuro do negócio.',['Projetos estratégicos','People Analytics','Visão de negócio']]};
    document.querySelectorAll('.journey-card').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.journey-card').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const d=journeyData[btn.dataset.journey],r=document.getElementById('journeyResult');if(d&&r)r.innerHTML=`<div><span class="journey-icon">→</span><div><strong>${d[0]}</strong><p>${d[1]}</p></div></div><div class="journey-points">${d[2].map(x=>`<span>${x}</span>`).join('')}</div>`}));
    document.querySelectorAll('[data-job]').forEach(btn=>btn.addEventListener('click',()=>{const box=document.getElementById('candidatura'),title=document.getElementById('jobTitle');if(box){box.style.display='block';if(title)title.textContent=`Candidate-se: ${btn.dataset.job}`;box.scrollIntoView({behavior:'smooth',block:'center'})}}));
    document.querySelectorAll('[data-feel]').forEach(btn=>btn.addEventListener('click',()=>{const r=document.getElementById('listenResult');if(r)r.innerHTML=`<strong>Obrigado por compartilhar.</strong><br>${btn.dataset.feel}. Sua percepção importa e merece acompanhamento.`}));
    const listen=document.getElementById('openListen');if(listen)listen.addEventListener('click',()=>document.querySelector('.listen')?.scrollIntoView({behavior:'smooth',block:'center'}));
  });
  if(!document.querySelector('link[href="premium.css"]')){const premium=document.createElement('link');premium.rel='stylesheet';premium.href='premium.css';document.head.appendChild(premium)}
})();
